// Side-effect imports — each file registers its cards' dogma handlers at
// module load time via registerDogma. Adding a card-set is one new import.
//
// Auto-regenerated by scripts/integrate-workflow.mjs after the Ages 2-10
// workflow run. Hand edits are fine; just keep one import per age file.
import './age1';
import './age2';
import './age3';
import './age4';
import './age5';
import './age6';
import './age7';
import './age8';
import './age9';
import './age10';
